server:
  port: 9002
spring:
  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
